name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '42 5 * * *'

jobs:
  build-in-container:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.36'
#          - '5.32'
#          - '5.30'
#          - '5.18'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester

    name: Build on Linux with Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Version of Perl
        run: |
            perl -v

      - name: Install Module::Install
        run: |
            cpanm --notest Module::Install

      - name: Install Dependencies
        run: |
            cpanm --notest --installdeps .

      - name: Regular tests
        run: |
            perl Makefile.PL
            make
            make manifest
            make test
            perl build_site.pl --sourcedir . --destdir ~/padre.perlide.org
            ./Build
            ./Build test

